// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Weidner_School_Final_Project.Models
{
    public partial class Assignment
    {
        public Assignment()
        {
            AssignmentsStudents = new HashSet<AssignmentsStudent>();
        }

        public int AssignmentId { get; set; }
        public int CourseId { get; set; }
        public string AssignmentName { get; set; }
        public string AssignmentDescription { get; set; }
        public DateTime? AssignmentDueDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<AssignmentsStudent> AssignmentsStudents { get; set; }
    }
}