// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Weidner_School_Final_Project.Models
{
    public partial class AssignmentsStudent
    {
        public int AssignmentsStudentsId { get; set; }
        public int AssignmentId { get; set; }
        public int StudentId { get; set; }

        public virtual Assignment Assignment { get; set; }
        public virtual Student Student { get; set; }
    }
}