// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Weidner_School_Final_Project.Models
{
    public partial class Course
    {
        public Course()
        {
            Assignments = new HashSet<Assignment>();
            CoursesStudents = new HashSet<CoursesStudent>();
        }

        public int CourseId { get; set; }
        public int InstructorId { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }

        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<CoursesStudent> CoursesStudents { get; set; }
    }
}